Initial modifications to whatwg/fetch fork
WinterTC55/fetch pull request #1
Opened 2022-11-08 17:43 UTC by Ethan-Arrowood

Initial modification to whatwg/fetch fork

2022-11-09 11:35 UTC, sheplu requested changes

2022-11-09 11:35 UTC, sheplu commented on README.md
>  For quick local iteration, run `make`. To verify your changes locally, run `make deploy`. See more
I think there is something missing after the `see more` now that you removed the bullet list ?

2022-11-09 14:55 UTC, Ethan-Arrowood commented on README.md
>  For quick local iteration, run `make`. To verify your changes locally, run `make deploy`. See more
Oh yeah I'll resolve that. Their markdown had all these weird line breaks in it

2022-11-10 17:00 UTC, Ethan-Arrowood commented
Open question:

What do we do with the "review-drafts" directory?

2023-01-10 10:06 UTC, andreubotella commented
> Open question:
> 
> What do we do with the "review-drafts" directory?

The review drafts are a WHATWG/W3C process thing, they don't really matter to us. A new review draft is added every 6 months, and updates are rare to nonexistent. So I guess the merge conflicts won't be too bad if we delete it.

2023-01-19 18:06 UTC, andreubotella commented on fetch.bs
>  Text Macro: LATESTRD 2022-06
```suggestion
Title: Fetch
Shortname: fetch
Group: wintercg
Status: w3c/CG-DRAFT
Level: none
URL: https://fetch.wintercg.org/
Repository: https://github.com/wintercg/fetch
Editor: TODO
```

Bikeshed has different defaults for WHATWG than for WinterCG (see https://github.com/tabatkins/bikeshed-boilerplate), and this is what's needed to get this spec to build. I removed the `TWITTER` and `LATESTRD` text macros because they're specific to the WHATWG boilerplate.

Bikeshed also requires the spec to have an editor. You can skip it by replacing the `Editor` line with [`No Editor: true`](https://tabatkins.github.io/bikeshed/#metadata-no-editor). Whether to include an editor, and if so whether we should keep Anne as the original editor or maybe have @Ethan-Arrowood is up to you all I guess.

2023-01-26 08:14 UTC, Ethan-Arrowood commented on fetch.bs
>  Text Macro: LATESTRD 2022-06
I'll add myself as editor as I will be taking the onus of maintaining the fork

2023-01-26 18:19 UTC, andreubotella approved these changes
LGTM

2023-01-26 20:03 UTC, merged