Relax forbidden header restrictions for non-browser runtimes
WinterTC55/fetch pull request #19
Opened 2023-03-07 16:34 UTC by andreubotella

Web browsers treat certain request and response headers as forbidden –forbidden request headers are impossible to set in requests, and forbidden response headers are always filtered off of even basic filtered response (i.e. responses for same-origin fetches).

While some of these forbidden request headers make sense generally (for example, `Date`, `Host`, `Transfer-Encoding`), others don't make sense for implementers that don't support CORS or cookies. And the only forbidden response headers (`Set-Cookie` and `Set-Cookie2`) only make sense for implementers that support cookies.

To allow different kinds of implementers with different requirements, this change adds a "conformance classes" section defining support for CORS and cookies. It then changes the definitions of forbidden request and response headers to depend on the user agent's conformance classes.

2023-03-07 17:22 UTC, andreubotella commented
Should `Set-Cookie` be a forbidden request header for all implementers?

2023-04-18 18:51 UTC, Ethan-Arrowood requested changes

2023-04-18 18:51 UTC, Ethan-Arrowood commented on fetch.bs
> + <dd>if it has a concept of an <a for=/>origin</a> which the current EcmaScript execution context
```suggestion
 <dd>if it has a concept of an <a for=/>origin</a> which the current ECMAScript execution context
```

2023-04-18 18:51 UTC, Ethan-Arrowood commented on fetch.bs
> + [[ORIGIN]]
Missing a `!` here? 
```suggestion
 [[!ORIGIN]]
```

2023-04-18 18:51 UTC, Ethan-Arrowood commented on fetch.bs
> + [[!COOKIES]])).
```suggestion
 [[!COOKIES]]).
```

2023-07-06 14:29 UTC, andreubotella commented on fetch.bs
> + [[ORIGIN]]
I think nowadays, the HTML spec defines origins, so that is a normative reference, whereas I was listing [*The Web Origin Concept*](https://www.rfc-editor.org/rfc/rfc6454) as a non-normative reference/explanation.

2023-07-26 15:19 UTC, jasnell approved these changes

2023-08-16 21:22 UTC, Ethan-Arrowood approved these changes

2023-08-16 21:22 UTC, merged